### ISSUE TITLE
Error fetching notification

### ISSUE THREAD

**Issue by homayeekazim** [gitscout/gitscout-feedback#153]
Started using gitscout last week. It was always stuck in syncing notifications and notifications were never fetched. After the recent update, it now shows this error under both unread and participating notification.

TypeError: Cannot read property 'replace' of null
    at Transformer (file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:6040:25)
    at Array.map (native)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:6096:17
From previous event:
    at fetchNotifications (file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:6095:67)
    at message (file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:6112:3)
    at onmessage (file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:6000:33)

**Comment by michael-lefebvre** [comment]
@homayeekazim we just published an update that must fix this problem. Let me know if it's ok for you.

**Comment by homayeekazim** [comment]
@michael-lefebvre - I can see notifications now. Thank you so much for the quick fix.
