### ISSUE TITLE
error report: "error: typeerror: failed to fetch"

### ISSUE THREAD

**Issue by olets** [gitscout/gitscout-feedback#176]
This error just popped up:

```Error: TypeError: Failed to fetch
    at file:///private/var/folders/xn/26nbvw6s6n30pfwf7rmz4tfw0000gn/T/AppTranslocation/4C7D3869-5182-4F65-B237-EDEAE36566EE/d/Gitscout.app/Contents/Resources/app.asar/workers.js:6090:23
From previous event:
    at loop (file:///private/var/folders/xn/26nbvw6s6n30pfwf7rmz4tfw0000gn/T/AppTranslocation/4C7D3869-5182-4F65-B237-EDEAE36566EE/d/Gitscout.app/Contents/Resources/app.asar/workers.js:5926:31)```

Related issue: I got that by clicking "copy to clipboard" in Gitscout's error report modal. Note that the copy missed the first line, `Error: TypeError: Failed to fetch`

**Comment by nijikokun** [comment]
Seeing this as well.

**Comment by stevenjohn** [comment]
Yes me too... shame as the product works very well apart from this error..

**Comment by stevenjohn** [comment]
Any ideas on how to fix this? Any update planned if not?

**Comment by michael-lefebvre** [comment]
Hi, I just reproduce this issue for the first time. Can you confirm me that it happen after you put your computer in sleep mode?

**Comment by stevenjohn** [comment]
Hi @michael-lefebvre - yes! Funnily enough I was just coming back here to tell you exactly that...

So if GS stays open as i work, it refreshes itself and tells me when there's new messages to process. If I close my laptop - or lose internet connection (I think) - i then see this message.

For sure I have got this message when I have been working for a few hours without closing the laptop, but i can say I get the message 100% after the laptop is reopened.

Hope this is useful.

Kind regards, Steve

**Comment by michael-lefebvre** [comment]
Hi, we now prevent the app to crash in [version 1.0.0-rc.1](https://github.com/gitscout/gitscout-feedback/issues/193) 😉 Thanks for your patience.
