### ISSUE TITLE
Very regular error you cannot recover from

### ISSUE THREAD

**Issue by stevenjohn** [gitscout/gitscout-feedback#178]
Product works perfectly apart from this.

Seems to lose connection, shows error with this debug..

Error: TypeError: Failed to fetch
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:6090:23
From previous event:
    at loop (file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:5926:31)

Kind regards, Steve

**Comment by stevenjohn** [comment]
Closing as duplicate
