### ISSUE TITLE
Consistent "uh-oh" error in the issue list pane

### ISSUE THREAD

**Issue by entendu** [gitscout/gitscout-feedback#183]
![image](https://cloud.githubusercontent.com/assets/276273/24214763/b9b7a012-0ef3-11e7-8456-2880ba7bd8b2.png)

```
Error: TypeError: Failed to fetch
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:6090:23
From previous event:
    at loop (file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:5926:31)
```

**Comment by entendu** [comment]
Happened again.
```
Error: TypeError: Failed to fetch
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:6090:23
From previous event:
    at loop (file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:5926:31)
```

**Comment by entendu** [comment]
This is an intensely obnoxious error that happens every time I wake from sleep.

cc: @areskub

**Comment by areskub** [comment]
Hey @entendu I think @michael-lefebvre has finally found what is causing this bug and he's already working on it. (Michael correct me if I'm wrong). It IS the most obnoxious error ever for now. We collectively agree. Sorry about that.

**Comment by brashrebel** [comment]
Stoked to find that this is being worked on. I'm also experiencing the problem. Any way I can help?
