### ISSUE TITLE
Error: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by stevenjohn** [gitscout/gitscout-feedback#197]
Seems to be related to coming back to the machine after sleeping it.

Anyone else seen this error?

Error: TypeError: Failed to fetch
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:6090:23
From previous event:
    at loop (file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:5926:31)

![screen shot 2017-06-02 at 09 40 09](https://cloud.githubusercontent.com/assets/32484/26708668/805cecac-4777-11e7-85ce-b8d806b6c8f3.png)

The product is getting better and better btw - even with these bugs it is still brilliant to use :)

**Comment by jccguimaraes** [comment]
same here

**Comment by stevenjohn** [comment]
Any news on this as its a bit of a pain... means rebooting and often having to reconnect to GH on a daily basis which really disturbs the "leave this app running and get notified about GH messages in realtime" which is its essence for me?

Thanks, Steve
