### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by shigurenimo** [gitscout/gitscout-feedback#225]
```
Error: TypeError: Failed to fetch
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:6090:23
From previous event:
    at loop (file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:5926:31)
```

**Comment by envygeeks** [comment]
This happens *every* time I come back from sleep.
